// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnw2JkkP1d0lSU3d8Wzmfb5aIKNUTAIwk',
    appId: '1:513634319009:web:039fede0c01037f6810ee0',
    messagingSenderId: '513634319009',
    projectId: 'cadoneghe-volley-app',
    authDomain: 'cadoneghe-volley-app.firebaseapp.com',
    storageBucket: 'cadoneghe-volley-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9tDEZ5wbpxyOBmItkZWp7FrkHLkp37Ig',
    appId: '1:513634319009:android:10b3bb317650048d810ee0',
    messagingSenderId: '513634319009',
    projectId: 'cadoneghe-volley-app',
    storageBucket: 'cadoneghe-volley-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjuRLTiKPDBr6julqX6cYkYX_AsWcX70',
    appId: '1:513634319009:ios:20b80894f50dbe5f810ee0',
    messagingSenderId: '513634319009',
    projectId: 'cadoneghe-volley-app',
    storageBucket: 'cadoneghe-volley-app.firebasestorage.app',
    iosBundleId: 'it.tom.cadoneghevolley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTjuRLTiKPDBr6julqX6cYkYX_AsWcX70',
    appId: '1:513634319009:ios:20b80894f50dbe5f810ee0',
    messagingSenderId: '513634319009',
    projectId: 'cadoneghe-volley-app',
    storageBucket: 'cadoneghe-volley-app.firebasestorage.app',
    iosBundleId: 'it.tom.cadoneghevolley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnw2JkkP1d0lSU3d8Wzmfb5aIKNUTAIwk',
    appId: '1:513634319009:web:225106de734e91dd810ee0',
    messagingSenderId: '513634319009',
    projectId: 'cadoneghe-volley-app',
    authDomain: 'cadoneghe-volley-app.firebaseapp.com',
    storageBucket: 'cadoneghe-volley-app.firebasestorage.app',
  );
}
